### ISSUE TITLE
ZXing creates wrong barcode (for text with leading asterisk?)

### ISSUE THREAD

**Issue by CharlyNapf** [zxing/zxing#923]
Hi,

this is a follow-up of issue  #806. Now we are using version 3.3.1 and it solves all issue reported in #806.

In our project we create data matrix barcodes using ZXing (core-3.3.1.jar and javase-3.3.1.jar) in this way:
```java
        final DataMatrixWriter barcode = new DataMatrixWriter();
        final BitMatrix bitMatrix = barcode.encode(text, BarcodeFormat.DATA_MATRIX, 0, 0);
```
We create an image (java.awt.Image) using the bit matrix and scan this barcode image afterwards (form screen or paper). In 99% percent of all cases the text of the scanned barcode image is identical to the the encoded text.

But in some cases we get another text. Examples:

* original text -> converted to barcode
* `*CH/GN1/022/00` -> `*CH/GN1/022/{00`

I suppose the leading asterisk causes again the problem.
![inf_01_zxingcreatewrongbarocde](https://user-images.githubusercontent.com/23717092/33834779-7110b9b4-de84-11e7-85be-655a257b14bb.png)

**Comment by srowen** [comment]
Not sure, can you debug to see where it goes wrong? are you sure the contents are wrong or somehow is it read back wrong?

**Comment by CharlyNapf** [comment]
I tried to debug, but I do not really understand the code.  I suppose the bug happens between step 1 and step 4 in `DataMatrixWriter.encode`
![inf_02_zxingdebugging](https://user-images.githubusercontent.com/23717092/33835908-2cf34ba8-de88-11e7-970e-28442dd618fa.png)

**Comment by srowen** [comment]
One simple step is to establish what decoder returns what for which encoder. That should narrow down where the behavior difference is.

**Comment by CharlyNapf** [comment]
I suppose you must help me again. I stepped into `HighLevelEncoder.encodeHighLevel` and I found 6 encoders, but no decoder.
![inf_03_zxingdebugging](https://user-images.githubusercontent.com/23717092/33841479-1e8da4e0-de98-11e7-85fa-d16ac2a8e79f.png)

**Comment by micjahn** [comment]
In my opinion the error is in the file EdifactEncoder at line 48.
`buffer.append((char) 31); //Unlatch`
If that line is removed the generated code will be correctly decoded. But I think that it is not correct for all cases. I don't have a datamatrix spec but I think the unlatching has to be handled different in some cases.
Other encoders handle it in the method `handleEOD`.
More important is that the EdifactEncoder uses the character 31 for unlatch. All others (X12, C40) uses the character 254.
If the line 48 is changed to
`buffer.append((char) 254); //Unlatch`
it works too.

**Comment by srowen** [comment]
You are likely right. I remember that latch/unlatch is complicated and seem to recall fixing problems like this in the past. I don't have the spec or the skill to pursue it at this point but would look at a pull request.

**Comment by axxel** [comment]
I have not tried this particular example, but the added '{' character looks very familiar to me. Could it be that #912 already fixed this?

**Comment by CharlyNapf** [comment]
If it #912 is part of release 3.3.1, then it is NOT fixed yes.
If it will be part of release 3.3.1 then I will wait for new new release. But I cannot find a milestone for the new release.

**Comment by srowen** [comment]
That change went in after 3.3.1. Can you build from master and try it? I can cut a snapshot release too

**Comment by CharlyNapf** [comment]
I have no development environment. 
So it would be nice it you could provide a snapshot.

**Comment by srowen** [comment]
I just pushed snapshot artifacts @CharlyNapf : https://oss.sonatype.org/content/repositories/snapshots/com/google/zxing/core/3.3.2-SNAPSHOT/

**Comment by CharlyNapf** [comment]
Thanks a lot, the 3.3.2-snapshot  works as expected, see attached image.
There are differences between the barcode images of ZXing and iText, I hope this is no bad sign.

**Comment by srowen** [comment]
OK, sounds like that other change fixed it. Yes the barcode could encode the same text differently because different encodings are chosen internally.

**Comment by CharlyNapf** [comment]
Thanks a lot for your help.

**Comment by CharlyNapf** [comment]
Sorry, my response from 18-Dec-2018 was wrong. The snapshot release 3.3.2 did NOT solve the issue, see ![inf_11_testedwithzxing332](https://user-images.githubusercontent.com/23717092/35038163-369a48d2-fb7a-11e7-87fe-a9edbc875c0f.png).

Can you please re-open the issue? Or should I create a new one.
