### ISSUE TITLE
ZXing 3.3.2 snapshot still creates wrong barcode for text with leading asterisk 

### ISSUE THREAD

**Issue by CharlyNapf** [zxing/zxing#960]
Hi,

this is a follow-up of issue #806, #923 and #944. Today I tested the official snapshot of version 3.3.2 and it does NOT solve the error reported in #923.

See ![err_01_zxing332-generateswrongbarcodeforleadingasterisk](https://user-images.githubusercontent.com/23717092/36494631-dcb6fb88-1732-11e8-8845-0f522bf5a91b.png)

Kind regards,
C. Napf

**Comment by srowen** [comment]
Hm, it's confusing to keep opening issues for the same thing. How is this different now? what tested successfully before that isn't working now? what change do you propose?

**Comment by axxel** [comment]
@CharlyNapf I'm not a Java guy, so I won't be able to help more than I did already by pointing out the fix I found for the c++ version. It seems you'll have to fire up a debugger yourself and try to find out why that fix is not working for you.

@srowen I would like to suggest to not close (legitimate) bug reports without prior confirmation from the reporter that her issue is indeed fixed.

**Comment by srowen** [comment]
@axxel he reported it was working at https://github.com/zxing/zxing/issues/806#issuecomment-305124221 https://github.com/zxing/zxing/issues/923#issuecomment-352466894 and you reported it fixed in https://github.com/zxing/zxing/issues/944#issuecomment-360764026 . Huh?

**Comment by axxel** [comment]
In 944 I said that I conclude the root problem should be fixed in the code base based on an experiment I did with the c++ port. And that I guessed that something is likely wrong with the snapshot he tested or maybe his own build still using the old one or whatever. Either way, he did not confirm the fix. That is what I meant.

**Comment by CharlyNapf** [comment]
I understand your confusion. I will repeat the **history** to clarify this topic:
* on 11-Dec-2017 I reported the issue #923
** on 18-Dec-2017 I tested with a snapshot - but unfortunately without the leading asterisk (my fault)
** on 18-Dec-2017 I reported that the issue was solved (also my fault)
* on 17-Jan-2018 I detected my fault and reported the issue again #944 
** it was closed because I tested only with a snapshot 
* on 21-Feb-2018 I tested again, this time with the official release - and with the leading asterisk
** the test failed again, so I created this issue #960.

So if I can help you debugging in JAVA I will do it. But I cannot understand the code. It is only readable for a specialist.

**Comment by srowen** [comment]
OK. It's more usual to comment on the existing issue rather than open new ones. It can be reopened if necessary. At this point, let's leave this open as the _only_ issue tracking this. However, nobody is working on this project. You'd have to separately open a pull request with a requested change for anything to happen.

**Comment by micjahn** [comment]
I checked out the c++ port. The result is that the content "*CH/GN1/022/00" only works when the selected shape is DataMatrix::SymbolShape::SQUARE.
The same is true for the .Net port (which I'm working on). The .Net port contains the same c++ fix as the java original from #944 .
In my opinion all three versions of zxing have the same problem. I know my comment doesn't fix anything but perhaps it clarifies some confusions.

**Comment by axxel** [comment]
@micjahn That info does indeed bring a new angle to the conversation. I quickly added the problematic string to the EncodeDecodeRectangle test in the DMEncodeDecodeTest.cpp and it seems to work just fine in the c++ port. Also the screenshot from @CharlyNapf shows a square code with the issue. How did you generate the rectangular code with the c++ port that shows the issue?

**Comment by micjahn** [comment]
I grabbed the code from here: https://github.com/axxel/zxing-cpp
I changed the following in DMEncodeDecodeTest.cpp
```
TEST(DMEncodeDecodeTest, EDIFACTWithEOD)
{
	TestEncodeDecode(L"https://test~[******]_");
	TestEncodeDecode(L"abc<->ABCDE");
	TestEncodeDecode(L"<ABCDEFG><ABCDEFGK>");
	TestEncodeDecode(L"*CH/GN1/022/00");
}
```
to
```
TEST(DMEncodeDecodeTest, EDIFACTWithEOD)
{
	TestEncodeDecode(L"https://test~[******]_");
	TestEncodeDecode(L"abc<->ABCDE");
	TestEncodeDecode(L"<ABCDEFG><ABCDEFGK>");
	TestEncodeDecode(L"*CH/GN1/022/00", DataMatrix::SymbolShape::NONE);
}
```

**Comment by axxel** [comment]
Thanks @micjahn for that insightful input. I reproduced the problem in the c++ code base and came up with this fix: https://github.com/nu-book/zxing-cpp/commit/e0db0989551c8810960ef2724a0b6dbbc98c0d52, which is inspired by a change in the original barcode4j source code to some other related issue: https://sourceforge.net/p/barcode4j/svn/221/.  I have the suspicion that this old change introduced a regression and I admit that my 'fix' might do just the same. That said: all my collected EDIFACT samples do work with all three shape options now.

A quick workaround that should work with 3.3.2 is to set the FORCE_SQUARE shape hint.

**Comment by srowen** [comment]
@axxel I wasn't clear if this is still an issue? the fix you mention is already merged into the code base here, or, something very similar at least.

**Comment by axxel** [comment]
@srowen Not that I know of, but I'd say @CharlyNapf is the person to ask whether his/her issue is now finally solved.

**Comment by CharlyNapf** [comment]
@srowen yes, I did and the result is good. I have tried to attach an image, but "something went really wrong", so you must believe me.

**Comment by CharlyNapf** [comment]
Thank you!
